version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: JWTAuth/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Host=db;Port=5432;Database=JWTAuthDb;Username=postgres;Password=MyPass@word
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyPass@word
      POSTGRES_DB: JWTAuthDb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=redis@password
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  db_data:
    driver: local

networks:
  backend:
    driver: bridge
